describe ("Fail Login Axia",() =>{
    it("Login procedure", ()=> {
        cy.clearCookies()
        cy.clearLocalStorage()
        cy.visit(('https://axia2-ui-qa.santextest.com/login'),{failOnStatusCode: false})
        cy.url().should('include', 'antextest.com/login')
        cy.log('Website Charged')
        cy.get('#email').clear()
        cy.get('#email').type('lorem')
        cy.get("body").click()
        cy.contains("Must be a valid e-mail.")
        cy.get('#email').clear()
        cy.get('#email').type('lorem@axia.com')
        cy.get('#password').clear()
        cy.get('#password').type('!"#$')
        cy.contains("Login").click()
        cy.contains("Login details are not correct, please try again")
    })
})